STYLES = [
    {
        "id": "calm_confirm",
        "label": "平静确认",
        "intensity": 0.5,
        "rate": 0.96,
        "pitch_shift_st": -0.5,
        "energy": 0.98,
        "pause_scale": 1.10,
        "instruct": "请用平静、确认、语速稍慢、语气稳定的方式说这句话。",
    },
    {
        "id": "serious_alert",
        "label": "严肃提醒",
        "intensity": 0.9,
        "rate": 1.05,
        "pitch_shift_st": -0.5,
        "energy": 1.12,
        "pause_scale": 0.95,
        "instruct": "请用严肃、清晰、略带急促、强调关键词的方式说这句话。",
    },
    {
        "id": "warm_encourage",
        "label": "温和安抚",
        "intensity": 0.7,
        "rate": 0.95,
        "pitch_shift_st": 1.0,
        "energy": 1.05,
        "pause_scale": 1.10,
        "instruct": "请用温和、安抚、语气亲切、节奏放松的方式说这句话。",
    },
    {
        "id": "friendly_welcome",
        "label": "友好欢迎",
        "intensity": 0.7,
        "rate": 1.0,
        "pitch_shift_st": 1.2,
        "energy": 1.05,
        "pause_scale": 1.05,
        "instruct": "请用友好、热情、上扬、轻快的方式说这句话。",
    },
    {
        "id": "focused_guide",
        "label": "专注指导",
        "intensity": 0.8,
        "rate": 0.92,
        "pitch_shift_st": 0.5,
        "energy": 1.08,
        "pause_scale": 1.15,
        "instruct": "请用专注、清晰、耐心、有层次感的方式说这句话。",
    },
    {
        "id": "neutral_report",
        "label": "中性播报",
        "intensity": 0.4,
        "rate": 1.0,
        "pitch_shift_st": 0.0,
        "energy": 0.95,
        "pause_scale": 1.00,
        "instruct": "请用中性、客观、均匀、像播报一样的方式说这句话。",
    },
    {
        "id": "energetic_boost",
        "label": "活力鼓励",
        "intensity": 0.85,
        "rate": 1.08,
        "pitch_shift_st": 1.5,
        "energy": 1.10,
        "pause_scale": 0.95,
        "instruct": "请用有活力、兴奋、上扬、稍微快一点的方式说这句话。",
    },
    {
        "id": "patient_repeat",
        "label": "耐心重复",
        "intensity": 0.6,
        "rate": 0.90,
        "pitch_shift_st": -1.0,
        "energy": 0.97,
        "pause_scale": 1.20,
        "instruct": "请用非常耐心、柔和、放慢节奏、像重复解释一样的方式说这句话。",
    },
    {
        "id": "curious_question",
        "label": "好奇询问",
        "intensity": 0.65,
        "rate": 0.98,
        "pitch_shift_st": 1.5,
        "energy": 1.00,
        "pause_scale": 1.15,
        "instruct": "请用好奇、疑问、上扬、自然停顿的方式说这句话。",
    },
    {
        "id": "apologetic",
        "label": "歉意解释",
        "intensity": 0.60,
        "rate": 0.90,
        "pitch_shift_st": 0.5,
        "energy": 0.90,
        "pause_scale": 1.25,
        "instruct": "请用抱歉、诚恳、语速稍慢、态度温和的方式说这句话。",
    },
]

STYLE_MAP = {item["id"]: item for item in STYLES}

REFERENCE_SENTENCE = "希望你以后能够做的比我还好呦。"
